## ----------------------------------------------------------------------
## Travis CI build script for Greenplum Database Open Source Project.
## ----------------------------------------------------------------------

language: c
sudo: false
cache:
  directories:
    - $HOME/gpdb-5.21.4

git:
  submodules: false

addons:
    apt:
        config:
            retries: true
        sources: &common_sources
            - ubuntu-toolchain-r-test
        packages: &common_packages
            - gcc-8
            - libxml2
            - libxml2-dev
            - libevent-dev
            - libperl-dev
            - g++-8
            - python-dev
            - python-yaml
            - libapr1-dev
            - libzstd1
            - libzstd1-dev

matrix:
    include:
        # OS and Compiler variations
        # ----------------------------------------------------------------
        #
        # Ubuntu Bionic, gcc 8
        - os: linux
          dist: bionic
          compiler: gcc
          env:
              - T=debug C=""
              - OVERRIDE_CC="CC=gcc-8" OVERRIDE_CXX="CXX=g++-8"
          addons:
              apt:
                  sources:
                      - *common_sources
                  packages:
                      - *common_packages
        # Ubuntu Xenial, clang 7
        - os: linux
          dist: xenial
          compiler: clang
          env:
              - T=debug C=""
              - OVERRIDE_CC="CC=clang-7" OVERRIDE_CXX="CXX=clang++-7"
          addons:
              apt:
                  sources:
                      - *common_sources
                      - llvm-toolchain-xenial-7
                  packages:
                      - *common_packages
                      - clang-7
        # macOS, XCode11
        - os: osx
          compiler: clang
          osx_image: xcode11
          env: T=macos
        #
        # Upgrade test
        # ----------------------------------------------------------------
        # Runs the pg_upgrade test_gpdb.sh script against the cached 5.x
        # build.
        - os: linux
          dist: bionic
          compiler: gcc
          env:
              - T=upgrade C=""
              - OVERRIDE_CC="CC=gcc-8" OVERRIDE_CXX="CXX=g++-8"
          addons:
              apt:
                  sources:
                      - *common_sources
                  packages:
                      - *common_packages
        #
        # Configuration variations
        # ----------------------------------------------------------------
        #
        # Debug build without any compression algorithms supplied
        - os: linux
          dist: bionic
          compiler: gcc
          env:
              - T=debug C="--without-zlib --without-libbz2 --without-zstd --without-quicklz"
              - OVERRIDE_CC="CC=gcc-8" OVERRIDE_CXX="CXX=g++-8"
          addons:
              apt:
                  sources: *common_sources
                  packages: *common_packages

## ----------------------------------------------------------------------
## Build tools
## ----------------------------------------------------------------------

python:
    - "2.7"

before_install:
    - eval "${OVERRIDE_CC}"
    - eval "${OVERRIDE_CXX}"

## ----------------------------------------------------------------------
## Install supporting Python modules
## ----------------------------------------------------------------------

install:
    - pip install --user --upgrade pip
    - pip install --user --pre psutil
    - pip install --user lockfile
    - pip install --user setuptools

## ----------------------------------------------------------------------
## Perform build:
## ----------------------------------------------------------------------

before_script:
    - ssh-keygen -t "rsa" -f ~/.ssh/id_rsa -N ""
    - cp ~/.ssh/{id_rsa.pub,authorized_keys}
    - |
      if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        if [ ! -e $HOME/gpdb-5.21.4/GNUmakefile ]; then
          (cd $HOME && \
           mkdir -p gpdb5 && \
           curl -LO https://github.com/greenplum-db/gpdb/archive/5.21.4.tar.gz && \
           tar -zxf 5.21.4.tar.gz && \
           cd gpdb-5.21.4 && \
           CC="gcc-8" CXX="g++-8" ./configure --prefix=$HOME/gpdb5/ --with-perl --with-python --disable-orca --disable-gpcloud && \
           make -s)
        fi
      fi

script:
  - |
      set -eo pipefail
      if [ "$T" = "debug" ]; then
        ./configure \
            --prefix=${TRAVIS_BUILD_DIR}/gpsql \
            --enable-cassert \
            --enable-debug \
            --enable-debug-extensions \
            --with-perl \
            --with-python \
            --disable-orca \
            --with-openssl \
            --with-ldap \
            --with-libcurl \
            --with-libxml \
            --enable-mapreduce \
            --enable-orafce \
            $C
        make -s install
        source ${TRAVIS_BUILD_DIR}/gpsql/greenplum_path.sh
        make -s unittest-check
        make -C gpAux/gpdemo cluster
        source gpAux/gpdemo/gpdemo-env.sh
        make -C src/test/regress installcheck-small
      fi
  - |
      set -eo pipefail
      if [ "$T" = "upgrade" ]; then
        ./configure \
            --prefix=${TRAVIS_BUILD_DIR}/gpsql \
            --with-perl \
            --with-python \
            --disable-orca \
            --disable-gpcloud \
            --disable-pxf \
            --with-libcurl \
            $C
        make -s install
        source ${TRAVIS_BUILD_DIR}/gpsql/greenplum_path.sh
        make -C gpAux/gpdemo cluster
        source gpAux/gpdemo/gpdemo-env.sh
        gpstop -aq
        unset MASTER_DATA_DIRECTORY
        unset PGPORT
        unset GPHOME
        mkdir -p $HOME/gpdb5
        pushd $HOME/gpdb-5.21.4
        make -s install
        source $HOME/gpdb5/greenplum_path.sh
        export DEFAULT_QD_MAX_CONNECT=10
        export NEW_BUFFERS="5000kB"
        make -C gpAux/gpdemo cluster || true
        cat /home/travis/gpdb-5.21.4/gpAux/gpdemo/datadirs/gpAdminLogs/gpinitsystem_20190909.log
        source gpAux/gpdemo/gpdemo-env.sh
        gpstop -aq
        unset MASTER_DATA_DIRECTORY
        unset PGPORT
        unset GPHOME
        popd
        bash ./src/bin/pg_upgrade/test_gpdb.sh -C -s -o $HOME/gpdb-5.21.4/gpAux/gpAux/gpdemo/datadirs/qddir/demoDataDir-1/ -B $HOME/gpdb5/bin -b $TRAVIS_BUILD_DIR/gpsql/bin
      fi
  - |
      set -eo pipefail
      if [ "$T" = "production" ]; then
        ./configure \
            --prefix=${TRAVIS_BUILD_DIR}/gpsql \
            --with-perl \
            --with-python \
            --disable-orca \
            --with-openssl \
            --with-ldap \
            --with-libcurl \
            --with-libxml \
            --enable-mapreduce \
            --enable-orafce \
            $C
        make -s install
        source ${TRAVIS_BUILD_DIR}/gpsql/greenplum_path.sh
        make -s unittest-check
        make -C gpAux/gpdemo cluster
        source gpAux/gpdemo/gpdemo-env.sh
        make -C src/test/regress installcheck-small
      fi
  - |
      set -eo pipefail
      if [ "$T" = "macos" ]; then
        ./configure \
            --prefix=${TRAVIS_BUILD_DIR}/gpsql \
            --with-perl \
            --with-python \
            --disable-orca \
            --enable-orafce \
            --disable-gpfdist \
            --disable-pxf \
            --disable-gpcloud \
            --without-zstd \
            $C
        make -s install
        source ${TRAVIS_BUILD_DIR}/gpsql/greenplum_path.sh
        make -s unittest-check
      fi

after_script:
  - source ${TRAVIS_BUILD_DIR}/gpsql/greenplum_path.sh
  - postgres --version
  - gpssh --version
